name: Auto Generate Markdown Files

on:
  push:
    paths:
      - 'static/files/*.pdf'
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录，便于检测更改

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run improved auto-generate script
        run: |
          python scripts/improved_auto_generate.py

      - name: Check for changes
        id: check_changes
        run: |
          git add content/materials/
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "自动生成Markdown文件 [skip ci]"
          git push
